"""empty message

Revision ID: 3952d893141d
Revises: 193bca0dac97
Create Date: 2021-12-09 14:53:09.132861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3952d893141d'
down_revision = '193bca0dac97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('idCountry', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'film', 'country', ['idCountry'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film', type_='foreignkey')
    op.drop_column('film', 'idCountry')
    # ### end Alembic commands ###
