"""empty message

Revision ID: 5e44251f07b8
Revises: 193bca0dac97
Create Date: 2021-12-09 18:32:11.517910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e44251f07b8'
down_revision = '193bca0dac97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('urlPhoto', sa.String(), nullable=True))
    op.add_column('scene', sa.Column('urlPhoto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'urlPhoto')
    op.drop_column('place', 'urlPhoto')
    # ### end Alembic commands ###
