"""empty message

Revision ID: 7735c784c9b2
Revises: cc1ce8952401
Create Date: 2021-12-27 16:01:04.495508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735c784c9b2'
down_revision = 'cc1ce8952401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('comment', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'body')
    # ### end Alembic commands ###
