"""empty message

Revision ID: 8c6cc5354a98
Revises: 7735c784c9b2
Create Date: 2021-12-30 15:54:28.295842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6cc5354a98'
down_revision = '7735c784c9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parentId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'parentId')
    # ### end Alembic commands ###
