"""empty message

Revision ID: 936323e075ac
Revises: 0bce56fc662b
Create Date: 2021-12-18 00:56:13.629843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936323e075ac'
down_revision = '0bce56fc662b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('idCountry', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'film', 'country', ['idCountry'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film', type_='foreignkey')
    op.drop_column('film', 'idCountry')
    # ### end Alembic commands ###
